export {default as Login} from './auth/Login';
export {default as Registration} from './auth/Registration';
export {default as Main} from './drawer/Main';
export {default as Coupons} from './drawer/Coupons';
export {default as Prices} from './drawer/Prices';
export {default as Map} from './drawer/Map';
export {default as Discounts} from './drawer/Discounts';
export {default as CustomDrawerContent} from './drawer/CustomDrawerContent';
export {default as Profile} from './drawer/Profile';
