export default {
  arrow: require('../assets/images/arrow.png'),
  barcode: require('../assets/images/barcode.png'),
  bg: require('../assets/images/bg.jpg'),
  bgBody: require('../assets/images/bgBody.jpg'),
  bgHeader: require('../assets/images/bgHeader.jpg'),
  logo: require('../assets/images/logo.png'),
  discount: require('../assets/images/discount.jpg'),
  ua: require('../assets/images/ua.png'),
  cross: require('../assets/images/cross.png'),
  edit: require('../assets/images/edit.png'),
  mainLogo: require('../assets/images/mainLogo.png'),
  menuProfile: require('../assets/images/menuProfile.png'),
  menuCoupons: require('../assets/images/menuCoupons.png'),
  menuPrices: require('../assets/images/menuPrices.png'),
  menuDiscounts: require('../assets/images/menuDiscounts.png'),
  menuMap: require('../assets/images/menuMap.png'),
  menuArrow: require('../assets/images/menuArrow.png'),
};
